- hosts: all  
  become: yes
  vars:
    root_html: /usr/share/nginx/html
    nginx_port: 8080
    web1: "{{'This is server ' + server_name + '!'}}"

  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: latest
      become: yes
      tags: nginx

    - name: install cowsay
      apt:
        name: cowsay
        state: latest
      become: yes

    - name: Say cow play
      include_tasks: say_cow.yml

    - name: update nginx index.html
      template:
        src: files/index.html
        dest: "{{root_html}}/index.html"
      become: yes 
      tags: nginx

    - name: update nginx config
      template:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
      become: yes  
      notify:
      - restart nginx    
      tags: nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: reloaded
      become: yes
      tags: nginx
