- hosts: balancer
  remote_user: qqadmin
  become: true
  vars:
    root_html: /usr/share/nginx/html
    nginx_port: 8083

  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: latest
      tags: nginx

    - name: update nginx index.html
      copy:
        src: files/index.html
        dest: "{{root_html}}/index.html" 
      tags: nginx

    - name: update nginx config
      template:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf  
      notify:
      - restart nginx    
      tags: nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: reloaded
      become: yes
      tags: nginx
