
- hosts: all
  vars:
    #path: /var/log/upstart/nginx.log
    #web1: "{{ansible_hostname}}"
    #web2: "{{'This is server ' + ansible_hostname + '!'}}"
    numbers: [3, 2, 6, 9, 0]

  tasks:
   - name: get max number
     debug: msg={{ numbers|sort }}
  
   - name: get unique values
     debug: msg={{ item }}
     loop: "{{ numbers }}"
   
   - name: get random value
     debug: msg={{ ['a', 'b', 'c'] | random }}
